# Generated by Django 5.2.7 on 2025-12-29 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
